// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Veiculo.proto

package proto;

public interface CreateVeiculoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.CreateVeiculoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.Veiculo veiculo = 1;</code>
   */
  boolean hasVeiculo();
  /**
   * <code>.proto.Veiculo veiculo = 1;</code>
   */
  proto.Veiculo getVeiculo();
  /**
   * <code>.proto.Veiculo veiculo = 1;</code>
   */
  proto.VeiculoOrBuilder getVeiculoOrBuilder();
}
