// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Veiculo.proto

package proto;

public interface DeleteVeiculoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.DeleteVeiculoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 veiculoId = 1;</code>
   */
  int getVeiculoId();
}
