// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Veiculo.proto

package proto;

/**
 * Protobuf type {@code proto.GetVeiculoResponse}
 */
public  final class GetVeiculoResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.GetVeiculoResponse)
    GetVeiculoResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetVeiculoResponse.newBuilder() to construct.
  private GetVeiculoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetVeiculoResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetVeiculoResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            proto.Veiculo.Builder subBuilder = null;
            if (veiculo_ != null) {
              subBuilder = veiculo_.toBuilder();
            }
            veiculo_ = input.readMessage(proto.Veiculo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(veiculo_);
              veiculo_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.VeiculoOuterClass.internal_static_proto_GetVeiculoResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.VeiculoOuterClass.internal_static_proto_GetVeiculoResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.GetVeiculoResponse.class, proto.GetVeiculoResponse.Builder.class);
  }

  public static final int VEICULO_FIELD_NUMBER = 1;
  private proto.Veiculo veiculo_;
  /**
   * <code>.proto.Veiculo veiculo = 1;</code>
   */
  public boolean hasVeiculo() {
    return veiculo_ != null;
  }
  /**
   * <code>.proto.Veiculo veiculo = 1;</code>
   */
  public proto.Veiculo getVeiculo() {
    return veiculo_ == null ? proto.Veiculo.getDefaultInstance() : veiculo_;
  }
  /**
   * <code>.proto.Veiculo veiculo = 1;</code>
   */
  public proto.VeiculoOrBuilder getVeiculoOrBuilder() {
    return getVeiculo();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (veiculo_ != null) {
      output.writeMessage(1, getVeiculo());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (veiculo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getVeiculo());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.GetVeiculoResponse)) {
      return super.equals(obj);
    }
    proto.GetVeiculoResponse other = (proto.GetVeiculoResponse) obj;

    boolean result = true;
    result = result && (hasVeiculo() == other.hasVeiculo());
    if (hasVeiculo()) {
      result = result && getVeiculo()
          .equals(other.getVeiculo());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasVeiculo()) {
      hash = (37 * hash) + VEICULO_FIELD_NUMBER;
      hash = (53 * hash) + getVeiculo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.GetVeiculoResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.GetVeiculoResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.GetVeiculoResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.GetVeiculoResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.GetVeiculoResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.GetVeiculoResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.GetVeiculoResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.GetVeiculoResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.GetVeiculoResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto.GetVeiculoResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.GetVeiculoResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.GetVeiculoResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.GetVeiculoResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.GetVeiculoResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.GetVeiculoResponse)
      proto.GetVeiculoResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.VeiculoOuterClass.internal_static_proto_GetVeiculoResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.VeiculoOuterClass.internal_static_proto_GetVeiculoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.GetVeiculoResponse.class, proto.GetVeiculoResponse.Builder.class);
    }

    // Construct using proto.GetVeiculoResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (veiculoBuilder_ == null) {
        veiculo_ = null;
      } else {
        veiculo_ = null;
        veiculoBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.VeiculoOuterClass.internal_static_proto_GetVeiculoResponse_descriptor;
    }

    @java.lang.Override
    public proto.GetVeiculoResponse getDefaultInstanceForType() {
      return proto.GetVeiculoResponse.getDefaultInstance();
    }

    @java.lang.Override
    public proto.GetVeiculoResponse build() {
      proto.GetVeiculoResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.GetVeiculoResponse buildPartial() {
      proto.GetVeiculoResponse result = new proto.GetVeiculoResponse(this);
      if (veiculoBuilder_ == null) {
        result.veiculo_ = veiculo_;
      } else {
        result.veiculo_ = veiculoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.GetVeiculoResponse) {
        return mergeFrom((proto.GetVeiculoResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.GetVeiculoResponse other) {
      if (other == proto.GetVeiculoResponse.getDefaultInstance()) return this;
      if (other.hasVeiculo()) {
        mergeVeiculo(other.getVeiculo());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proto.GetVeiculoResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proto.GetVeiculoResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private proto.Veiculo veiculo_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        proto.Veiculo, proto.Veiculo.Builder, proto.VeiculoOrBuilder> veiculoBuilder_;
    /**
     * <code>.proto.Veiculo veiculo = 1;</code>
     */
    public boolean hasVeiculo() {
      return veiculoBuilder_ != null || veiculo_ != null;
    }
    /**
     * <code>.proto.Veiculo veiculo = 1;</code>
     */
    public proto.Veiculo getVeiculo() {
      if (veiculoBuilder_ == null) {
        return veiculo_ == null ? proto.Veiculo.getDefaultInstance() : veiculo_;
      } else {
        return veiculoBuilder_.getMessage();
      }
    }
    /**
     * <code>.proto.Veiculo veiculo = 1;</code>
     */
    public Builder setVeiculo(proto.Veiculo value) {
      if (veiculoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        veiculo_ = value;
        onChanged();
      } else {
        veiculoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.proto.Veiculo veiculo = 1;</code>
     */
    public Builder setVeiculo(
        proto.Veiculo.Builder builderForValue) {
      if (veiculoBuilder_ == null) {
        veiculo_ = builderForValue.build();
        onChanged();
      } else {
        veiculoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.proto.Veiculo veiculo = 1;</code>
     */
    public Builder mergeVeiculo(proto.Veiculo value) {
      if (veiculoBuilder_ == null) {
        if (veiculo_ != null) {
          veiculo_ =
            proto.Veiculo.newBuilder(veiculo_).mergeFrom(value).buildPartial();
        } else {
          veiculo_ = value;
        }
        onChanged();
      } else {
        veiculoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.proto.Veiculo veiculo = 1;</code>
     */
    public Builder clearVeiculo() {
      if (veiculoBuilder_ == null) {
        veiculo_ = null;
        onChanged();
      } else {
        veiculo_ = null;
        veiculoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.proto.Veiculo veiculo = 1;</code>
     */
    public proto.Veiculo.Builder getVeiculoBuilder() {
      
      onChanged();
      return getVeiculoFieldBuilder().getBuilder();
    }
    /**
     * <code>.proto.Veiculo veiculo = 1;</code>
     */
    public proto.VeiculoOrBuilder getVeiculoOrBuilder() {
      if (veiculoBuilder_ != null) {
        return veiculoBuilder_.getMessageOrBuilder();
      } else {
        return veiculo_ == null ?
            proto.Veiculo.getDefaultInstance() : veiculo_;
      }
    }
    /**
     * <code>.proto.Veiculo veiculo = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        proto.Veiculo, proto.Veiculo.Builder, proto.VeiculoOrBuilder> 
        getVeiculoFieldBuilder() {
      if (veiculoBuilder_ == null) {
        veiculoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            proto.Veiculo, proto.Veiculo.Builder, proto.VeiculoOrBuilder>(
                getVeiculo(),
                getParentForChildren(),
                isClean());
        veiculo_ = null;
      }
      return veiculoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.GetVeiculoResponse)
  }

  // @@protoc_insertion_point(class_scope:proto.GetVeiculoResponse)
  private static final proto.GetVeiculoResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.GetVeiculoResponse();
  }

  public static proto.GetVeiculoResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetVeiculoResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetVeiculoResponse>() {
    @java.lang.Override
    public GetVeiculoResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetVeiculoResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetVeiculoResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetVeiculoResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.GetVeiculoResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

