// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Veiculo.proto

package proto;

/**
 * Protobuf type {@code proto.ListVeiculoResponse}
 */
public  final class ListVeiculoResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.ListVeiculoResponse)
    ListVeiculoResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListVeiculoResponse.newBuilder() to construct.
  private ListVeiculoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListVeiculoResponse() {
    veiculo_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ListVeiculoResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              veiculo_ = new java.util.ArrayList<proto.Veiculo>();
              mutable_bitField0_ |= 0x00000001;
            }
            veiculo_.add(
                input.readMessage(proto.Veiculo.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        veiculo_ = java.util.Collections.unmodifiableList(veiculo_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.VeiculoOuterClass.internal_static_proto_ListVeiculoResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.VeiculoOuterClass.internal_static_proto_ListVeiculoResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.ListVeiculoResponse.class, proto.ListVeiculoResponse.Builder.class);
  }

  public static final int VEICULO_FIELD_NUMBER = 1;
  private java.util.List<proto.Veiculo> veiculo_;
  /**
   * <code>repeated .proto.Veiculo veiculo = 1;</code>
   */
  public java.util.List<proto.Veiculo> getVeiculoList() {
    return veiculo_;
  }
  /**
   * <code>repeated .proto.Veiculo veiculo = 1;</code>
   */
  public java.util.List<? extends proto.VeiculoOrBuilder> 
      getVeiculoOrBuilderList() {
    return veiculo_;
  }
  /**
   * <code>repeated .proto.Veiculo veiculo = 1;</code>
   */
  public int getVeiculoCount() {
    return veiculo_.size();
  }
  /**
   * <code>repeated .proto.Veiculo veiculo = 1;</code>
   */
  public proto.Veiculo getVeiculo(int index) {
    return veiculo_.get(index);
  }
  /**
   * <code>repeated .proto.Veiculo veiculo = 1;</code>
   */
  public proto.VeiculoOrBuilder getVeiculoOrBuilder(
      int index) {
    return veiculo_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < veiculo_.size(); i++) {
      output.writeMessage(1, veiculo_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < veiculo_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, veiculo_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.ListVeiculoResponse)) {
      return super.equals(obj);
    }
    proto.ListVeiculoResponse other = (proto.ListVeiculoResponse) obj;

    boolean result = true;
    result = result && getVeiculoList()
        .equals(other.getVeiculoList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getVeiculoCount() > 0) {
      hash = (37 * hash) + VEICULO_FIELD_NUMBER;
      hash = (53 * hash) + getVeiculoList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.ListVeiculoResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.ListVeiculoResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.ListVeiculoResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.ListVeiculoResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.ListVeiculoResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.ListVeiculoResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.ListVeiculoResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.ListVeiculoResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.ListVeiculoResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto.ListVeiculoResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.ListVeiculoResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.ListVeiculoResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.ListVeiculoResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.ListVeiculoResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.ListVeiculoResponse)
      proto.ListVeiculoResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.VeiculoOuterClass.internal_static_proto_ListVeiculoResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.VeiculoOuterClass.internal_static_proto_ListVeiculoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.ListVeiculoResponse.class, proto.ListVeiculoResponse.Builder.class);
    }

    // Construct using proto.ListVeiculoResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getVeiculoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (veiculoBuilder_ == null) {
        veiculo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        veiculoBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.VeiculoOuterClass.internal_static_proto_ListVeiculoResponse_descriptor;
    }

    @java.lang.Override
    public proto.ListVeiculoResponse getDefaultInstanceForType() {
      return proto.ListVeiculoResponse.getDefaultInstance();
    }

    @java.lang.Override
    public proto.ListVeiculoResponse build() {
      proto.ListVeiculoResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.ListVeiculoResponse buildPartial() {
      proto.ListVeiculoResponse result = new proto.ListVeiculoResponse(this);
      int from_bitField0_ = bitField0_;
      if (veiculoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          veiculo_ = java.util.Collections.unmodifiableList(veiculo_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.veiculo_ = veiculo_;
      } else {
        result.veiculo_ = veiculoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.ListVeiculoResponse) {
        return mergeFrom((proto.ListVeiculoResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.ListVeiculoResponse other) {
      if (other == proto.ListVeiculoResponse.getDefaultInstance()) return this;
      if (veiculoBuilder_ == null) {
        if (!other.veiculo_.isEmpty()) {
          if (veiculo_.isEmpty()) {
            veiculo_ = other.veiculo_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureVeiculoIsMutable();
            veiculo_.addAll(other.veiculo_);
          }
          onChanged();
        }
      } else {
        if (!other.veiculo_.isEmpty()) {
          if (veiculoBuilder_.isEmpty()) {
            veiculoBuilder_.dispose();
            veiculoBuilder_ = null;
            veiculo_ = other.veiculo_;
            bitField0_ = (bitField0_ & ~0x00000001);
            veiculoBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getVeiculoFieldBuilder() : null;
          } else {
            veiculoBuilder_.addAllMessages(other.veiculo_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proto.ListVeiculoResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proto.ListVeiculoResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<proto.Veiculo> veiculo_ =
      java.util.Collections.emptyList();
    private void ensureVeiculoIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        veiculo_ = new java.util.ArrayList<proto.Veiculo>(veiculo_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.Veiculo, proto.Veiculo.Builder, proto.VeiculoOrBuilder> veiculoBuilder_;

    /**
     * <code>repeated .proto.Veiculo veiculo = 1;</code>
     */
    public java.util.List<proto.Veiculo> getVeiculoList() {
      if (veiculoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(veiculo_);
      } else {
        return veiculoBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .proto.Veiculo veiculo = 1;</code>
     */
    public int getVeiculoCount() {
      if (veiculoBuilder_ == null) {
        return veiculo_.size();
      } else {
        return veiculoBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .proto.Veiculo veiculo = 1;</code>
     */
    public proto.Veiculo getVeiculo(int index) {
      if (veiculoBuilder_ == null) {
        return veiculo_.get(index);
      } else {
        return veiculoBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .proto.Veiculo veiculo = 1;</code>
     */
    public Builder setVeiculo(
        int index, proto.Veiculo value) {
      if (veiculoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVeiculoIsMutable();
        veiculo_.set(index, value);
        onChanged();
      } else {
        veiculoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.Veiculo veiculo = 1;</code>
     */
    public Builder setVeiculo(
        int index, proto.Veiculo.Builder builderForValue) {
      if (veiculoBuilder_ == null) {
        ensureVeiculoIsMutable();
        veiculo_.set(index, builderForValue.build());
        onChanged();
      } else {
        veiculoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.Veiculo veiculo = 1;</code>
     */
    public Builder addVeiculo(proto.Veiculo value) {
      if (veiculoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVeiculoIsMutable();
        veiculo_.add(value);
        onChanged();
      } else {
        veiculoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.Veiculo veiculo = 1;</code>
     */
    public Builder addVeiculo(
        int index, proto.Veiculo value) {
      if (veiculoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVeiculoIsMutable();
        veiculo_.add(index, value);
        onChanged();
      } else {
        veiculoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto.Veiculo veiculo = 1;</code>
     */
    public Builder addVeiculo(
        proto.Veiculo.Builder builderForValue) {
      if (veiculoBuilder_ == null) {
        ensureVeiculoIsMutable();
        veiculo_.add(builderForValue.build());
        onChanged();
      } else {
        veiculoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.Veiculo veiculo = 1;</code>
     */
    public Builder addVeiculo(
        int index, proto.Veiculo.Builder builderForValue) {
      if (veiculoBuilder_ == null) {
        ensureVeiculoIsMutable();
        veiculo_.add(index, builderForValue.build());
        onChanged();
      } else {
        veiculoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto.Veiculo veiculo = 1;</code>
     */
    public Builder addAllVeiculo(
        java.lang.Iterable<? extends proto.Veiculo> values) {
      if (veiculoBuilder_ == null) {
        ensureVeiculoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, veiculo_);
        onChanged();
      } else {
        veiculoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .proto.Veiculo veiculo = 1;</code>
     */
    public Builder clearVeiculo() {
      if (veiculoBuilder_ == null) {
        veiculo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        veiculoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .proto.Veiculo veiculo = 1;</code>
     */
    public Builder removeVeiculo(int index) {
      if (veiculoBuilder_ == null) {
        ensureVeiculoIsMutable();
        veiculo_.remove(index);
        onChanged();
      } else {
        veiculoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .proto.Veiculo veiculo = 1;</code>
     */
    public proto.Veiculo.Builder getVeiculoBuilder(
        int index) {
      return getVeiculoFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .proto.Veiculo veiculo = 1;</code>
     */
    public proto.VeiculoOrBuilder getVeiculoOrBuilder(
        int index) {
      if (veiculoBuilder_ == null) {
        return veiculo_.get(index);  } else {
        return veiculoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .proto.Veiculo veiculo = 1;</code>
     */
    public java.util.List<? extends proto.VeiculoOrBuilder> 
         getVeiculoOrBuilderList() {
      if (veiculoBuilder_ != null) {
        return veiculoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(veiculo_);
      }
    }
    /**
     * <code>repeated .proto.Veiculo veiculo = 1;</code>
     */
    public proto.Veiculo.Builder addVeiculoBuilder() {
      return getVeiculoFieldBuilder().addBuilder(
          proto.Veiculo.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.Veiculo veiculo = 1;</code>
     */
    public proto.Veiculo.Builder addVeiculoBuilder(
        int index) {
      return getVeiculoFieldBuilder().addBuilder(
          index, proto.Veiculo.getDefaultInstance());
    }
    /**
     * <code>repeated .proto.Veiculo veiculo = 1;</code>
     */
    public java.util.List<proto.Veiculo.Builder> 
         getVeiculoBuilderList() {
      return getVeiculoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        proto.Veiculo, proto.Veiculo.Builder, proto.VeiculoOrBuilder> 
        getVeiculoFieldBuilder() {
      if (veiculoBuilder_ == null) {
        veiculoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            proto.Veiculo, proto.Veiculo.Builder, proto.VeiculoOrBuilder>(
                veiculo_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        veiculo_ = null;
      }
      return veiculoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.ListVeiculoResponse)
  }

  // @@protoc_insertion_point(class_scope:proto.ListVeiculoResponse)
  private static final proto.ListVeiculoResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.ListVeiculoResponse();
  }

  public static proto.ListVeiculoResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListVeiculoResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListVeiculoResponse>() {
    @java.lang.Override
    public ListVeiculoResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ListVeiculoResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ListVeiculoResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListVeiculoResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.ListVeiculoResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

