// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Veiculo.proto

package proto;

public interface ListVeiculoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ListVeiculoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.Veiculo veiculo = 1;</code>
   */
  java.util.List<proto.Veiculo> 
      getVeiculoList();
  /**
   * <code>repeated .proto.Veiculo veiculo = 1;</code>
   */
  proto.Veiculo getVeiculo(int index);
  /**
   * <code>repeated .proto.Veiculo veiculo = 1;</code>
   */
  int getVeiculoCount();
  /**
   * <code>repeated .proto.Veiculo veiculo = 1;</code>
   */
  java.util.List<? extends proto.VeiculoOrBuilder> 
      getVeiculoOrBuilderList();
  /**
   * <code>repeated .proto.Veiculo veiculo = 1;</code>
   */
  proto.VeiculoOrBuilder getVeiculoOrBuilder(
      int index);
}
