// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Veiculo.proto

package proto;

public interface ListVeiculoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ListVeiculoRequest)
    com.google.protobuf.MessageOrBuilder {
}
