// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Veiculo.proto

package proto;

public interface VeiculoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Veiculo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string marca = 2;</code>
   */
  java.lang.String getMarca();
  /**
   * <code>string marca = 2;</code>
   */
  com.google.protobuf.ByteString
      getMarcaBytes();

  /**
   * <code>string modelo = 3;</code>
   */
  java.lang.String getModelo();
  /**
   * <code>string modelo = 3;</code>
   */
  com.google.protobuf.ByteString
      getModeloBytes();

  /**
   * <code>string anoFab = 4;</code>
   */
  java.lang.String getAnoFab();
  /**
   * <code>string anoFab = 4;</code>
   */
  com.google.protobuf.ByteString
      getAnoFabBytes();

  /**
   * <code>string anoMod = 5;</code>
   */
  java.lang.String getAnoMod();
  /**
   * <code>string anoMod = 5;</code>
   */
  com.google.protobuf.ByteString
      getAnoModBytes();

  /**
   * <code>string preco = 6;</code>
   */
  java.lang.String getPreco();
  /**
   * <code>string preco = 6;</code>
   */
  com.google.protobuf.ByteString
      getPrecoBytes();
}
