// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Veiculo.proto

package proto;

public final class VeiculoOuterClass {
  private VeiculoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Veiculo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Veiculo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CreateVeiculoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CreateVeiculoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CreateVeiculoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CreateVeiculoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_UpdateVeiculoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_UpdateVeiculoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_UpdateVeiculoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_UpdateVeiculoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DeleteVeiculoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_DeleteVeiculoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DeleteVeiculoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_DeleteVeiculoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_GetVeiculoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_GetVeiculoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_GetVeiculoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_GetVeiculoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ListVeiculoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ListVeiculoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ListVeiculoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ListVeiculoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rVeiculo.proto\022\005proto\"c\n\007Veiculo\022\n\n\002id\030" +
      "\001 \001(\005\022\r\n\005marca\030\002 \001(\t\022\016\n\006modelo\030\003 \001(\t\022\016\n\006" +
      "anoFab\030\004 \001(\t\022\016\n\006anoMod\030\005 \001(\t\022\r\n\005preco\030\006 " +
      "\001(\t\"7\n\024CreateVeiculoRequest\022\037\n\007veiculo\030\001" +
      " \001(\0132\016.proto.Veiculo\"8\n\025CreateVeiculoRes" +
      "ponse\022\037\n\007veiculo\030\001 \001(\0132\016.proto.Veiculo\"7" +
      "\n\024UpdateVeiculoRequest\022\037\n\007veiculo\030\001 \001(\0132" +
      "\016.proto.Veiculo\"8\n\025UpdateVeiculoResponse" +
      "\022\037\n\007veiculo\030\001 \001(\0132\016.proto.Veiculo\")\n\024Del" +
      "eteVeiculoRequest\022\021\n\tveiculoId\030\001 \001(\005\"*\n\025" +
      "DeleteVeiculoResponse\022\021\n\tveiculoId\030\001 \001(\005" +
      "\"&\n\021GetVeiculoRequest\022\021\n\tveiculoId\030\001 \001(\005" +
      "\"5\n\022GetVeiculoResponse\022\037\n\007veiculo\030\001 \001(\0132" +
      "\016.proto.Veiculo\"\024\n\022ListVeiculoRequest\"6\n" +
      "\023ListVeiculoResponse\022\037\n\007veiculo\030\001 \003(\0132\016." +
      "proto.Veiculo2\375\002\n\016VeiculoService\022J\n\rCrea" +
      "teVeiculo\022\033.proto.CreateVeiculoRequest\032\034" +
      ".proto.CreateVeiculoResponse\022J\n\rUpdateVe" +
      "iculo\022\033.proto.UpdateVeiculoRequest\032\034.pro" +
      "to.UpdateVeiculoResponse\022J\n\rDeleteVeicul" +
      "o\022\033.proto.DeleteVeiculoRequest\032\034.proto.D" +
      "eleteVeiculoResponse\022A\n\nGetVeiculo\022\030.pro" +
      "to.GetVeiculoRequest\032\031.proto.GetVeiculoR" +
      "esponse\022D\n\013ListVeiculo\022\031.proto.ListVeicu" +
      "loRequest\032\032.proto.ListVeiculoResponseB\002P" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_Veiculo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Veiculo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Veiculo_descriptor,
        new java.lang.String[] { "Id", "Marca", "Modelo", "AnoFab", "AnoMod", "Preco", });
    internal_static_proto_CreateVeiculoRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_CreateVeiculoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CreateVeiculoRequest_descriptor,
        new java.lang.String[] { "Veiculo", });
    internal_static_proto_CreateVeiculoResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_CreateVeiculoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CreateVeiculoResponse_descriptor,
        new java.lang.String[] { "Veiculo", });
    internal_static_proto_UpdateVeiculoRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_UpdateVeiculoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_UpdateVeiculoRequest_descriptor,
        new java.lang.String[] { "Veiculo", });
    internal_static_proto_UpdateVeiculoResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_proto_UpdateVeiculoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_UpdateVeiculoResponse_descriptor,
        new java.lang.String[] { "Veiculo", });
    internal_static_proto_DeleteVeiculoRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_proto_DeleteVeiculoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_DeleteVeiculoRequest_descriptor,
        new java.lang.String[] { "VeiculoId", });
    internal_static_proto_DeleteVeiculoResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_proto_DeleteVeiculoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_DeleteVeiculoResponse_descriptor,
        new java.lang.String[] { "VeiculoId", });
    internal_static_proto_GetVeiculoRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_proto_GetVeiculoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_GetVeiculoRequest_descriptor,
        new java.lang.String[] { "VeiculoId", });
    internal_static_proto_GetVeiculoResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_proto_GetVeiculoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_GetVeiculoResponse_descriptor,
        new java.lang.String[] { "Veiculo", });
    internal_static_proto_ListVeiculoRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_proto_ListVeiculoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ListVeiculoRequest_descriptor,
        new java.lang.String[] { });
    internal_static_proto_ListVeiculoResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_proto_ListVeiculoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ListVeiculoResponse_descriptor,
        new java.lang.String[] { "Veiculo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
